apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp-container
          image: wiraaji2301/myapp-amd64:v3
          ports:
            - containerPort: 3000
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
          env:
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: myapp-secret
                  key: SECRET_KEY_BASE
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 8080
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 8080
          #   initialDelaySeconds: 60
          #   periodSeconds: 30
      volumes:
        - name: myapp-volume
          hostPath:
      resources:
        requests:
          memory: '768Mi' # Rails butuh memory tinggi
          cpu: '300m'
        limits:
          memory: '1.5Gi' # Beri headroom besar
          cpu: '800m'

---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: myapp-route
spec:
  to:
    kind: Service
    name: myapp-service
  port:
    targetPort: 3000
  tls:
    termination: edge
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: myapp-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myapp-deployment
  minReplicas: 1
  maxReplicas: 15
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70 # Turunkan dari 80%
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 130 # Turunkan dari 140%
  # behavior:
  #   scaleUp:
  #     stabilizationWindowSeconds: 300 # 5 menit
  #     policies:
  #       - type: Percent
  #         value: 50
  #         periodSeconds: 60
  #   scaleDown:
  #     stabilizationWindowSeconds: 600 # 10 menit
  #     policies:
  #       - type: Percent
  #         value: 20
  #         periodSeconds: 60
